/* Portfolio project data */
const allProjects = [
  {
    id: "grace",
    title: "A college-access platform at national scale",
    img: "grace.jpg",
    tier: "featured",
    body: "<strong>Role:</strong> Grew into lead developer and primary client contact.<br/><br/><strong>Scale:</strong> Used nationally by advisers and program staff to support 400k+ students. Student tasks, outreach campaigns, and reporting are driven by each student's data and configurable rules — not fixed workflows.<br/><br/><strong>How I lead:</strong> Linear scoping and prioritization, stakeholder demos, PR review with an emphasis on test coverage, production deployments, release notes, and production issue triage in Sentry.<br/><br/><strong>Shipped highlights:</strong><ul><li>Greenfield student portal with onboarding, profile management, auto-generated college-readiness tasks, and parent-submitted records (deployed; wide release in progress).</li><li>Data Requests approval workflow — students submit applications, scholarships, tests, and financial aid for adviser review before commit, integrated with the task engine and exposed via web UI and AI tools.</li><li>AI assistant with RAG over scoped knowledge bases, function-calling, streaming chat, and adviser escalation.</li><li>AI conversational SMS on Twilio with two-way conversation, campaign-driven outreach, phone verification, and opt-in/out handling (built and deployed; full student rollout pending).</li></ul>",
    linkNote: "Private platform — happy to walk through on a call.",
    tags: ["Laravel", "Vue.js", "TypeScript", "Hybridly", "AI", "Twilio", "OpenAI", "Sentry"],
  },
  {
    id: "translash",
    title: "A bold site for a bold initiative",
    img: "translash.jpeg",
    tier: "client-full",
    body: "TransLash tells trans stories to save trans lives. <a href='https://www.hops-and-vines.com/' target='_blank'>Alix Hopfengaertner-Vigneault</a> and <a href='https://www.kailajacques.com/' target='_blank'>Kaila Jacques</a> designed a bold new site, and I was lead developer on the team that built it out. The site won a <a href='https://winners.webbyawards.com/2025/websites-and-mobile-sites/general-desktop-mobile-sites/activism/321914/translash-media' target='_blank'>2025 Webby Award</a>. Built on WordPress with the Laravel/Sage ecosystem.<br/><br/><strong>Highlights:</strong> the <a href='https://translash.org/projects/legislation-dashboard/' target='_blank'>Legislation Dashboard</a> fetches data daily from an external API and renders interactive D3.js charts; Spotify integration auto-imports new podcast episodes as draft posts; scroll-driven animations and sticky layouts throughout.",
    link: "https://translash.org/",
    linkText: "Check it out",
    tags: ["D3.js", "API integration", "WordPress", "Laravel/Sage", "Animation", "Alpine.js"],
  },
  {
    id: "acumen",
    title: "Acumen",
    img: "acumen.jpg",
    tier: "client-compact",
    summary: "Built a custom WordPress REST API and a multi-component Vue.js <a href='https://acumen.org/where-we-work/' target='_blank'>map app</a> — separate endpoints for programs, portfolio companies, and taxonomy filters, tied to the site's custom post types and ACF data model.",
    link: "https://acumen.org/where-we-work/",
    tags: ["WordPress", "Laravel/Sage", "REST API", "Vue.js"],
  },
  {
    id: "artsmidwest",
    title: "Arts Midwest",
    img: "artsmidwest.jpeg",
    tier: "client-compact",
    summary: "Award-winning WordPress site; built a custom REST API powering the <a href='https://artsmidwest.org/impact/' target='_blank'>impact page</a> — an interactive SVG map with grantee data and story blocks that respond to map state (Alpine.js).",
    link: "https://artsmidwest.org/impact/",
    tags: ["WordPress", "Laravel/Sage", "REST API", "Alpine.js"],
  },
  {
    id: "spf",
    title: "Chart labels that don't overlap",
    img: "spf.jpeg",
    tier: "craft",
    summary: "Custom canvas layout logic when Chart.js doughnuts couldn't place labels without overlap — geometry and placement code where the library stopped short. <a href='https://helpstpauls.com/annual-report/#by-the-numbers' target='_blank'>See the annual report</a>.",
    link: "https://helpstpauls.com/annual-report/#by-the-numbers",
    tags: ["Chart.js", "Canvas", "WordPress"],
  },
  {
    id: "game-of-life",
    title: "Conway's Game of Life: The Game",
    img: "game.png",
    tier: "craft",
    summary: "DOM-based cellular automaton with a drag-and-drop pattern library — state updates and performance constraints in plain JavaScript. <a href='https://github.com/fraserpage/the-game-of-life-the-game' target='_blank'>Code on GitHub</a>.",
    link: "https://fraserpage.github.io/the-game-of-life-the-game/",
    tags: ["Vanilla JavaScript", "Algorithms"],
  },
  {
    id: "tic-tac-toe",
    title: "Resizable Tic Tac Toe",
    img: "tic.png",
    tier: "craft",
    summary: "Any board size, player count, or win length. The interesting bit was a grid search algorithm to detect winning states across diagonals and dimensions. <a href='https://github.com/fraserpage/ResizableTicTacToe' target='_blank'>Code on GitHub</a>.",
    link: "https://fraserpage.github.io/ResizableTicTacToe/",
    tags: ["Vanilla JavaScript", "Algorithms"],
  },
  {
    id: "ic2021",
    title: "Chat-themed year in review",
    img: "IC2021.png",
    tier: "craft",
    summary: "Interactive mini-site with hidden easter eggs and chat-bubble reactions persisted via the WordPress REST API — API-first interactivity before that was my day job. <a href='https://ilercampbell.com/2021/' target='_blank'>See the 2021 review</a>.",
    link: "https://ilercampbell.com/2021/",
    tags: ["WordPress", "REST API"],
  },
  {
    id: "wedding",
    title: "Firebase, fun forms, and playful interactivity for my wedding website",
    img: "wedding.png",
    tier: "craft",
    body: "A labor of love — a playful RSVP site on Firebase with save-as-you-go forms and custom guest URLs. Move your mouse and we watch; click the heart to shoot an arrow and make us kiss. On mobile, drag the bow to aim.",
    link: "https://kasia-fraser.love/rsvp/v4jXBVDBjTyz7YDY9vDxVjmm",
    linkText: "Try Doug's RSVP page",
    tags: ["Vanilla JavaScript", "Firebase"],
  },
];

function projectsByTier(tier) {
  return allProjects.filter(p => p.tier === tier);
}
